services:
  minio:
    image: quay.io/minio/minio
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./data/minio:/data"
    environment:
      MINIO_ROOT_USER: "username"
      MINIO_ROOT_PASSWORD: "password"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8080:15672"
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "pucksmart"
      RABBITMQ_DEFAULT_PASS: "pucksmart"
      RABBITMQ_DEFAULT_VHOST: "pucksmart"
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: pucksmart
      POSTGRES_PASSWORD: pucksmart