services:
  minio:
    image: quay.io/minio/minio
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./data/minio:/data"
    environment:
      MINIO_ROOT_USER: "username"
      MINIO_ROOT_PASSWORD: "password"
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pucksmart
      POSTGRES_PASSWORD: pucksmart
    ports:
      - '5432:5432'
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"