services:
  minio:
    image: quay.io/minio/minio
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: "username"
      MINIO_ROOT_PASSWORD: "password"
  redis:
    image: redis
    ports:
      - "6379:6379"