# Generated by Django 5.0.2 on 2024-03-26 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HttpSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("e_tag", models.CharField(max_length=64)),
                ("last_refreshed", models.DateTimeField()),
                ("blob_path", models.CharField(max_length=256)),
            ],
        ),
    ]
