# Generated by Django 5.0.2 on 2024-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httpsource",
            name="e_tag",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
