# Generated by Django 5.0.2 on 2024-03-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_alter_nhlplayer_birth_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nhlplayer",
            name="handedness",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
