# Generated by Django 5.0.2 on 2024-02-27 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Franchise",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=64)),
                ("common_name", models.CharField(max_length=64)),
                ("place_name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("season", models.CharField(max_length=8)),
                ("game_type", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("abbreviation", models.CharField(max_length=3)),
                (
                    "franchise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stats.franchise",
                    ),
                ),
            ],
        ),
    ]
