# Generated by Django 5.0.2 on 2024-03-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("formatted_season_id", models.CharField(max_length=7)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("preseason_start_date", models.DateTimeField()),
                ("regular_season_end_date", models.DateTimeField()),
            ],
        ),
    ]
