# Generated by Django 5.0.2 on 2024-03-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="preseason_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
