# Generated by Django 5.0.2 on 2024-03-01 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_alter_season_preseason_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="away_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="games_as_away_team",
                to="stats.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="games_as_home_team",
                to="stats.team",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="stats.season"
            ),
        ),
    ]
