# Generated by Django 5.0.2 on 2024-03-16 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_faceoff_shot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_id", models.IntegerField()),
                ("player_id", models.IntegerField()),
                ("period", models.SmallIntegerField()),
                ("start_time", models.IntegerField()),
                ("end_time", models.IntegerField()),
                ("duration", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="stats.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="stats.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "shift_id")},
            },
        ),
    ]
